include:
  # Left Split (Central) With Bluetooth - Enable Studio RPC/Unlocking
  - board: nice_nano
    shield: scylla_left
    snippet: studio-rpc-usb-uart
    cmake-args:
      - -DCONFIG_ZMK_SPLIT=y
      - -DCONFIG_ZMK_WIRELESS=y
      - -DCONFIG_ZMK_STUDIO_LOCKING=n
      - -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y  # Explicit central for split
    artifact-name: keyboard_left

  # Right Split (Peripheral) With Bluetooth - Studio RPC needed for full Studio support
  - board: nice_nano
    shield: scylla_right
    snippet: studio-rpc-usb-uart  # Added for Studio RPC support
    cmake-args:
      - -DCONFIG_ZMK_SPLIT=y
      - -DCONFIG_ZMK_WIRELESS=y  # Explicit Bluetooth enable
    artifact-name: keyboard_right

  # Reset both splits with this firmware before flashing.
  - board: nice_nano
    shield: settings_reset
    artifact-name: keyboard_reset
