include:
  # Left Split (Central) With Bluetooth - Enable Studio RPC/Unlocking
  - board: nice_nano
    shield: scylla_left
    snippet: studio-rpc-usb-uart
    cmake-args:
      - -DCONFIG_ZMK_SPLIT=y
      - -DCONFIG_ZMK_STUDIO=y
      - -DCONFIG_ZMK_STUDIO_LOCKING=n
      - -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y  # Explicit central for split
    artifact-name: left_split_bluetooth_studio

  # Right Split (Peripheral) With Bluetooth - No Studio RPC needed
  - board: nice_nano
    shield: scylla_right
    cmake-args:
      - -DCONFIG_ZMK_SPLIT=y
    artifact-name: right_split_bluetooth

  # Reset both splits with this firmware before flashing.
  - board: nice_nano
    shield: settings_reset
    artifact-name: keyboard_reset
