include:
  # Левая (Central) - Studio RPC только здесь!
  - board: nice_nano
    shield: scylla_left
    snippet: studio-rpc-usb-uart  # Только слева!
    cmake-args:
      - -DCONFIG_ZMK_SPLIT=y
      - -DCONFIG_BT=y
      - -DCONFIG_ZMK_STUDIO_LOCKING=n
      - -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    artifact-name: keyboard_left

  # Правая (Peripheral) - ЧИСТЫЙ Bluetooth!
  - board: nice_nano
    shield: scylla_right
    cmake-args:  # Без snippet!
      - -DCONFIG_ZMK_SPLIT=y
      - -DCONFIG_BT=y
      - -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: keyboard_right

  # Reset
  - board: nice_nano
    shield: settings_reset
    artifact-name: keyboard_reset
