include:
  # Левая (Central) - Studio RPC только здесь!
  - board: nice_nano
    shield: scylla_left
    snippet: studio-rpc-usb-uart  # Только слева!
    cmake-args:
      - -DCONFIG_ZMK_SPLIT=y
      - -DCONFIG_ZMK_WIRELESS=y
      - -DCONFIG_ZMK_STUDIO_LOCKING=n
      - -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
      - -DCONFIG_BT_CTLR_PHY_2M=n    # Отключить 2Mbps PHY (Mac issue)
      - -DCONFIG_ZMK_BLE_PASSKEY_ENTRY=y  # Passkey для Mac
    artifact-name: keyboard_left

  # Правая (Peripheral) - ЧИСТЫЙ Bluetooth!
  - board: nice_nano
    shield: scylla_right
    snippet: studio-rpc-usb-uart  # Добавлен для поддержки RPC
    cmake-args:
      - -DCONFIG_ZMK_SPLIT=y
      - -DCONFIG_ZMK_WIRELESS=y
      - -DCONFIG_BT_CTLR_PHY_2M=n    # Согласованная настройка с левой половиной
      - -DCONFIG_ZMK_BLE_PASSKEY_ENTRY=y  # Согласованная настройка безопасности
    artifact-name: keyboard_right

  # Reset
  - board: nice_nano
    shield: settings_reset
    artifact-name: keyboard_reset
